model: unconditional
diffusion_config: diffusion_small_config
normalization: mean
state_dim: 1
observation_dim: 1
dataset: custom:sinusoidal
freq: H
context_length: 8
prediction_length: 2
dt: 0.05
samples: 5000
lr: 1.e-3
q: 0.1
init_skip: False
gradient_clip_val: 0.5
max_epochs: 200 # 50-100 for real training    #changed from 50 to 5 for testing
num_batches_per_epoch: 128
batch_size: 64
# Used only in callback,
# the final evaluation uses 100 samples
num_samples: 16
sampler: ddpm
sampler_params:
  guidance: quantile
  scale: 2
use_validation_set: True
eval_every: 50
device: cuda:0 # "cuda" or "cpu"
setup: forecasting