# Evaluation configuration
model: unconditional
diffusion_config: diffusion_small_config
normalization: mean
use_features: false
use_lags: true
lambda_reg: 1.0
freq: H  # Will be auto-corrected per dataset
context_length: 312  # Changed for consistency with kdd_cup
prediction_length: 24
lr: 1.e-3  # Not used for evaluation
init_skip: true
sampler: ddpm
sampler_params:
  guidance: quantile
  scale: 2
device: cuda:1  # Changed from cuda:0 to avoid memory issues
batch_size: 16  # Added to control memory usage
dropout_rate: 0.3
