model: unconditional
diffusion_config: diffusion_small_config
normalization: mean
use_features: false
use_lags: true
dataset: pedestrian_counts
freq: H
context_length: 336
prediction_length: 24
lr: 5.e-4
init_skip: true
gradient_clip_val: 0.5
max_epochs: 1000
num_batches_per_epoch: 128
batch_size: 64
dropout_rate: 0.01
lambda_reg: 1.0
score_loss_type: l2  # ← ADD THIS LINE
sampler: ddpm
sampler_params:
  guidance: quantile
  scale: 2
use_validation_set: true
eval_every: 50
device: cuda:1
setup: forecasting
