# TSDiff config for pedestrian_counts dataset
model: unconditional
diffusion_config: diffusion_small_config
normalization: mean
use_features: false
use_lags: true
dataset: pedestrian_counts
freq: H                      # Confirmed hourly frequency
context_length: 336          # Standardized (14 days * 24 hours)
prediction_length: 24        # Standardized (24 hour forecast window)
lr: 5.e-4                   # Lower LR for continual learning
init_skip: true
gradient_clip_val: 0.5
max_epochs: 1000
num_batches_per_epoch: 128
batch_size: 64
dropout_rate: 0.3 
sampler: ddpm
sampler_params:
  guidance: quantile
  scale: 2
use_validation_set: true
eval_every: 50
device: cuda:0
setup: forecasting
