model: unconditional
diffusion_config: diffusion_small_config
normalization: mean #mean, minmax, maxabs
observation_dim: 1
dataset: custom:sinusoidal
freq: H
context_length: 50
prediction_length: 50
dt: 0.05
data_samples: 5000
lr: 1.e-3
q: 0.0
r: 0.1
init_skip: False
gradient_clip_val: 0.5
max_epochs: 250 # 50-100 for real trainin
num_batches_per_epoch: 100
batch_size: 64
# Used only in callback,
# the final evaluation uses 100 samples
num_samples: 16
sampler: ddpm
sampler_params:
  guidance: quantile
  scale: 2
eval_every: 50
device: cpu # "cuda:0" for windows, "mps" for mac ONLY FOR TRAINING(breaks during forecasts), "cpu" for default
setup: forecasting
#checkpoint_path: D:\Users\MichaelPetrizzo2025\Continual_TSDiff\lightning_logs\version_110_10kmean\best_checkpoint.ckpt
checkpoint_path: /Users/monicastudent/Downloads/Continual_TSDiff/lightning_logs/version_7/best_checkpoint.ckpt