checkpoint: ./continual_learning_dropout_03_pipeline/step_4_uber_tlc_hourly/training/uber_tlc_hourly_checkpoint_best.pth
config:
  checkpoint_path: ./continual_learning_dropout_03_pipeline/step_4_uber_tlc_hourly/training/uber_tlc_hourly_checkpoint_best.pth
  context_length: 336
  device: cuda:0
  diffusion_config: diffusion_small_config
  dropout_rate: 0.3
  eval_datasets:
  - pedestrian_counts
  freq: H
  init_skip: true
  lr: 0.001
  model: unconditional
  normalization: mean
  num_samples: 100
  prediction_length: 24
  sampler: ddpm
  sampler_params:
    guidance: quantile
    scale: 2
  use_features: false
  use_lags: true
evaluation_settings:
  device: cuda:0
  num_samples: 100
results:
- ND: 0.9629305537758155
  NRMSE: 2.605454030437136
  checkpoint: ./continual_learning_dropout_03_pipeline/step_4_uber_tlc_hourly/training/uber_tlc_hourly_checkpoint_best.pth
  dataset: pedestrian_counts
  frequency: H
  mean_wQuantileLoss: 0.9430641786209674
  num_samples: 100
  success: true
